services:
  postgres:
    image: postgres:16.3
    container_name: sneakzone_database
    environment:
      POSTGRES_DB: sneakzone
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 96250cba14b93844816e9f0e9507cece92799e146b9d303971084ef2ec38ddba
    volumes:
      - pgdata:/var/lib/postgresql/data
      # If you have initialization scripts, uncomment the next line
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sneakzone"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
