version: "3.8"

services:
  postgres:
    image: postgres:16.3
    container_name: sneakzone_database
    environment:
      POSTGRES_DB: sneakzone
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 96250cba14b93844816e9f0e9507cece92799e146b9d303971084ef2ec38ddba
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sneakzone"]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3434/api
    container_name: sneakzone_client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=sneakzone
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecurepassword
      - PORT=3434
      - JWT_ACCESS_SECRET_KEY=your_access_secret_key_here
      - JWT_REFRESH_SECRET_KEY=your_refresh_secret_key_here
      - CLIENT_URL=http://localhost:3000
      - NODE_ENV_APP=development
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_USER=
      - SMTP_PASSWORD=
    container_name: sneakzone_server
    ports:
      - "3434:3434"
    depends_on:
      - postgres

volumes:
  postgres-data: